version: 1
sequences:
- protein:
    id: A
    sequence: SGPVPSRARVYTDVNTHRPSEYWDYESHVVEWGNQDDYQLVRKLGRGKYSEVFEAINITNNEKVVVKILKPVAAAKIKREIKILENLRGGPNIITLADIVKDPVSRTPALVFEHVNNTDFKQLYQTLTDYDIRFYMYEILKALDYCHSMGIMHRDVKPHNVMIDHEHRKLRLIDWGLAEFYHPGQEYNVRVASRYFKGPELLVDYQMYDYSLDMWSLGCMLASMIFRKEPFFHGHDNYDQLVRIAKVLGTEDLYDYIDKYNIELDPRFNDILGRHSRKRWERFVHSENQHLVSPEALDFLDKLLRYDHQSRLTAREAMEHPYFYTVVK
    msa: hackathon_data/datasets/asos_public/msa/6FVF.csv
- ligand:
    id: B
    smiles: COc1c(c2cc(ccc2[nH]1)F)C(=O)OCC3CCN(CC3)CCNS(=O)(=O)c4ccccc4
