version: 1
sequences:
- protein:
    id: A
    sequence: GAMDPSSPNYDKWEMERTDITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVSAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKRGT
    msa: hackathon_data/datasets/asos_public/msa/3K5V.csv
- ligand:
    id: B
    smiles: c1cc(cc(c1)C(=O)N)c2cc(ncn2)Nc3ccc(cc3)OC(F)(F)F
constraints:
- pocket:
    binder: B
    contacts:
    - - A
      - 1
    - - A
      - 2
    - - A
      - 3
    - - A
      - 4
    - - A
      - 5
    - - A
      - 6
    - - A
      - 7
    - - A
      - 8
    - - A
      - 9
    - - A
      - 10
    - - A
      - 11
    - - A
      - 12
    - - A
      - 13
    - - A
      - 14
    - - A
      - 15
    - - A
      - 16
    - - A
      - 17
    - - A
      - 18
    - - A
      - 19
    - - A
      - 20
    max_distance: 6.0
    force: true
