version: 1
sequences:
- protein:
    id: A
    sequence: IEGYECQPIFLNVLEAIEPGVVCAGHDNNQPDSFAALLSSLNELGERQLVHVVKWAKALPGFRNLHVDDQMAVIQYSWMGLMVFAMGWRSFTNVNSRMLYFAPDLVFNEYRMHKSRMYSQCVRMRHLSQEFGWLQITPQEFLCMKALLLFSIIPVDGLKNQKFFDELRMNYIKELDRIIACKRKNPTSCSRRFYQLTKLLDSVQPIARELHQFTFDLLIKSHMVSVDFPEMMAEIISVQVPKILSGKVKPIYFHTQ
    msa: hackathon_data/datasets/asos_public/msa/2AX9.csv
- ligand:
    id: B
    smiles: CC(CBr)(C(=O)Nc1ccc(c(c1)C(F)(F)F)[N+](=O)[O-])O
