version: 1
sequences:
- protein:
    id: A
    sequence: CQPIFLNVLEAIEPGVVCAGHDNNQPDSFAALLSSLNELGERQLVHVVKWAKALPGFRNLHVDDQMAVIQYSWMGLMVFAMGWRSFTNVNSRMLYFAPDLVFNEYRMHKSRMYSQCVRMRHLSQEFGWLQITPQEFLCMKALLLFSIIPVDGLKNQKFFDELRMNYIKELDRIIACKRKNPTSCSRRFYQLTKLLDSVQPIARELHQFTFDLLIKSHMVSVDFPEMMAEIISVQVPKILSGKVKPIYFHTQ
    msa: hackathon_data/datasets/asos_public/msa/2PIO.csv
- ligand:
    id: B
    smiles: CC12CCC(=O)CC1CCC3C2CCC4(C3CCC4O)C
