version: 1
sequences:
- protein:
    id: A
    sequence: GAMDPSSPNYDKWEMERTDITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVSAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKRGT
    msa: hackathon_data/datasets/asos_public/msa/3K5V.csv
- ligand:
    id: B
    smiles: c1cc(cc(c1)C(=O)N)c2cc(ncn2)Nc3ccc(cc3)OC(F)(F)F
