version: 1
sequences:
- protein:
    id: A
    sequence: AADVYVPDEWEVAREKITMSRELGQGSFGMVYEGVAKGVVKDEPETRVAIKTVNEAASMRERIEFLNEASVMKEFNCHHVVRLLGVVSQGQPTLVIMELMTRGDLKSYLRSLRPAMANNPVLAPPSLSKMIQMAGEIADGMAYLNANKFVHRDLAARNCMVAEDFTVKIGDFGMTRDIYETDYYRKGGKGLLPVRWMSPESLKDGVFTTYSDVWSFGVVLWEIATLAEQPYQGLSNEQVLRFVMEGGLLDKPDNCPDMLFELMRMCWQYNPKMRPSFLEIISSIKEEMEPGFREVSFYYSEENK
    msa: hackathon_data/datasets/asos_public/msa/3LW0.csv
- ligand:
    id: B
    smiles: c1cc2c(c[nH]c2c(c1)C(=O)NC3CCN(CC3)CCCCc4c[nH]c5c4cc(cc5)C#N)C#N
