version: 1
sequences:
- protein:
    id: A
    sequence: ASLTEIEHLVQSVCKSYRETCQLRLEDLLRQRSNIFSREEVTGYQRKSMWEMWERCAHHLTEAIQYVVEFAKRLSGFMELCQNDQIVLLKAGAMEVVLVRMCRAYNADNRTVFFEGKYGGMELFRALGCSELISSIFDFSHSLSALHFSEDEIALYTALVLINAHRPGLQEKRKVEQLQYNLELAFHHHLCKTHRQSILAKLPPKGKLRSLCSQHVERLQIFQHLHPIVVQAAFPPLYKELFS
    msa: hackathon_data/datasets/asos_public/msa/4YPQ.csv
- ligand:
    id: B
    smiles: c1ccc2c(c1)c(nn2C(=O)c3c(cccc3Cl)C(F)(F)F)c4ccc(cc4)C(=O)O
